---

- hosts: localhost
  connection: local
  remote_user: root
  become: yes
  roles:
    - {role: jdauphant.nginx, tags: nginx}
    #- {role: cycloid.sensu, tags: sensu}
  tasks:
   - file: dest=/opt/fooooo state=touch
   - command: id
     #become: true
