#!/bin/bash

export DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"

echo "# Received : $SOURCE_COMMIT"

echo "=> Building latest"
docker build --build-arg ANSIBLE_VERSION=v1 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

for version in $(cat .ansible_versions); do
    echo "=> Building $version"
    docker build --build-arg ANSIBLE_VERSION=$version -f $DOCKERFILE_PATH -t $DOCKER_REPO:v$version .
done
