#!/bin/bash

set -x

export DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"
env

echo "# Received : $SOURCE_COMMIT"
echo "=> Building latest"
docker build --build-arg ANSIBLE_VERSION="v1" -f $DOCKERFILE_PATH -t $IMAGE_NAME .

#docker build --build-arg version=2 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

