#!/bin/bash

set -x
env

echo "# Received : $SOURCE_COMMIT"
echo "=> Building latest"
docker build --build-arg version=1 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

#docker build --build-arg version=2 -f $DOCKERFILE_PATH -t $IMAGE_NAME .

